name: Nightly Build

on:
  schedule:
    # Run every night at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  nightly-test:
    name: Nightly Test Suite
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x, 21.x]
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run extended test suite
        run: |
          npm test
          npm run test:e2e
          
      - name: Generate comprehensive coverage
        run: npm run test:coverage:ci
        
      - name: Run performance benchmarks
        run: npm run test:performance
        
      - name: Security audit
        run: npm audit --audit-level=low
        
      - name: Upload nightly results
        uses: actions/upload-artifact@v4
        with:
          name: nightly-results-${{ matrix.node-version }}
          path: |
            coverage/
            test-results/
          retention-days: 30
          
      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Nightly build failed - Node.js ${{ matrix.node-version }}`,
              body: `The nightly build failed for Node.js ${{ matrix.node-version }}.
              
              **Workflow:** ${context.workflow}
              **Run ID:** ${context.runId}
              **Commit:** ${context.sha}
              
              Please check the workflow logs for details.`,
              labels: ['bug', 'ci-failure']
            });

  dependency-check:
    name: Dependency Security Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Check for outdated packages
        run: npm outdated || true
        
      - name: Security audit
        run: npm audit --audit-level=low
        
      - name: Create dependency report
        run: |
          echo "# Dependency Report" > dependency-report.md
          echo "Generated on: $(date)" >> dependency-report.md
          echo "" >> dependency-report.md
          echo "## Outdated Packages" >> dependency-report.md
          npm outdated --json > outdated.json || true
          echo "" >> dependency-report.md
          echo "## Security Audit" >> dependency-report.md
          npm audit --json > audit.json || true
          
      - name: Upload dependency report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-report
          path: |
            dependency-report.md
            outdated.json
            audit.json
          retention-days: 30